<?xml version="1.0" encoding="utf-8"?><Database Name="Gestion_Pharmacie" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=Gestion_Pharmacie;Integrated Security=True" SettingsObjectName="PHARMACIE.Properties.Settings" SettingsPropertyName="Gestion_PharmacieConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CATEGORIE_DU_MEDICAMENT" Member="CATEGORIE_DU_MEDICAMENT">
    <Type Name="CATEGORIE_DU_MEDICAMENT">
      <Column Name="code_categ" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="libelle_categ" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="CATEGORIE_DU_MEDICAMENT_MEDICAMENT" Member="MEDICAMENT" ThisKey="code_categ" OtherKey="code_categ" Type="MEDICAMENT" />
    </Type>
  </Table>
  <Table Name="dbo.COMMANDE" Member="COMMANDE">
    <Type Name="COMMANDE">
      <Column Name="code_facture" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="code_medicament" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="qte_vendue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FACTURE_COMMANDE" Member="FACTURE" ThisKey="code_facture" OtherKey="code_facture" Type="FACTURE" IsForeignKey="true" />
      <Association Name="MEDICAMENT_COMMANDE" Member="MEDICAMENT" ThisKey="code_medicament" OtherKey="code_medicament" Type="MEDICAMENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FACTURE" Member="FACTURE">
    <Type Name="FACTURE">
      <Column Name="code_facture" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="date_facturation" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="montant" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id_utilisateur" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="code_ord" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FACTURE_COMMANDE" Member="COMMANDE" ThisKey="code_facture" OtherKey="code_facture" Type="COMMANDE" />
      <Association Name="ORDONNANCE_FACTURE" Member="ORDONNANCE" ThisKey="code_ord" OtherKey="code_ord" Type="ORDONNANCE" IsForeignKey="true" />
      <Association Name="UTILISATEUR_FACTURE" Member="UTILISATEUR" ThisKey="id_utilisateur" OtherKey="id_utilisateur" Type="UTILISATEUR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FOURNISSEUR" Member="FOURNISSEUR">
    <Type Name="FOURNISSEUR">
      <Column Name="id_fournisseur" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nom_f" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="prenom_f" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="adresse_f" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tel_f" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FOURNISSEUR_STOCK" Member="STOCK" ThisKey="id_fournisseur" OtherKey="id_fournisseur" Type="STOCK" />
    </Type>
  </Table>
  <Table Name="dbo.MEDECIN" Member="MEDECIN">
    <Type Name="MEDECIN">
      <Column Name="id_medecin" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nom_complet_medecin" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="adresse_medecin" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="MEDECIN_ORDONNANCE" Member="ORDONNANCE" ThisKey="id_medecin" OtherKey="id_medecin" Type="ORDONNANCE" />
    </Type>
  </Table>
  <Table Name="dbo.MEDICAMENT" Member="MEDICAMENT">
    <Type Name="MEDICAMENT">
      <Column Name="code_medicament" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nom_medicament" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="qte_en_stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_exp" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_utilisateur" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="code_categ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MEDICAMENT_COMMANDE" Member="COMMANDE" ThisKey="code_medicament" OtherKey="code_medicament" Type="COMMANDE" />
      <Association Name="MEDICAMENT_MEDICAMENT_AVEC_ORD" Member="MEDICAMENT_AVEC_ORD" ThisKey="code_medicament" OtherKey="code_medicament" Type="MEDICAMENT_AVEC_ORD" />
      <Association Name="MEDICAMENT_STOCK" Member="STOCK" ThisKey="code_medicament" OtherKey="code_medicament" Type="STOCK" />
      <Association Name="CATEGORIE_DU_MEDICAMENT_MEDICAMENT" Member="CATEGORIE_DU_MEDICAMENT" ThisKey="code_categ" OtherKey="code_categ" Type="CATEGORIE_DU_MEDICAMENT" IsForeignKey="true" />
      <Association Name="UTILISATEUR_MEDICAMENT" Member="UTILISATEUR" ThisKey="id_utilisateur" OtherKey="id_utilisateur" Type="UTILISATEUR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MEDICAMENT_AVEC_ORD" Member="MEDICAMENT_AVEC_ORD">
    <Type Name="MEDICAMENT_AVEC_ORD">
      <Column Name="code_medicament" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="code_ord" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="MEDICAMENT_MEDICAMENT_AVEC_ORD" Member="MEDICAMENT" ThisKey="code_medicament" OtherKey="code_medicament" Type="MEDICAMENT" IsForeignKey="true" />
      <Association Name="ORDONNANCE_MEDICAMENT_AVEC_ORD" Member="ORDONNANCE" ThisKey="code_ord" OtherKey="code_ord" Type="ORDONNANCE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ORDONNANCE" Member="ORDONNANCE">
    <Type Name="ORDONNANCE">
      <Column Name="code_ord" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="date_consult" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_medecin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ORDONNANCE_FACTURE" Member="FACTURE" ThisKey="code_ord" OtherKey="code_ord" Type="FACTURE" />
      <Association Name="ORDONNANCE_MEDICAMENT_AVEC_ORD" Member="MEDICAMENT_AVEC_ORD" ThisKey="code_ord" OtherKey="code_ord" Type="MEDICAMENT_AVEC_ORD" />
      <Association Name="MEDECIN_ORDONNANCE" Member="MEDECIN" ThisKey="id_medecin" OtherKey="id_medecin" Type="MEDECIN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STOCK" Member="STOCK">
    <Type Name="STOCK">
      <Column Name="code_stock" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="qte_entre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_entre" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="code_medicament" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_fournisseur" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MEDICAMENT_STOCK" Member="MEDICAMENT" ThisKey="code_medicament" OtherKey="code_medicament" Type="MEDICAMENT" IsForeignKey="true" />
      <Association Name="FOURNISSEUR_STOCK" Member="FOURNISSEUR" ThisKey="id_fournisseur" OtherKey="id_fournisseur" Type="FOURNISSEUR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UTILISATEUR" Member="UTILISATEUR">
    <Type Name="UTILISATEUR">
      <Column Name="id_utilisateur" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nom_ut" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="prenom_ut" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="adresse_ut" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tel_ut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="app_identifiant" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="mot_de_passe" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Association Name="UTILISATEUR_FACTURE" Member="FACTURE" ThisKey="id_utilisateur" OtherKey="id_utilisateur" Type="FACTURE" />
      <Association Name="UTILISATEUR_MEDICAMENT" Member="MEDICAMENT" ThisKey="id_utilisateur" OtherKey="id_utilisateur" Type="MEDICAMENT" />
    </Type>
  </Table>
</Database>